### PR TITLE
Update ca.text

### PR DESCRIPTION
**Pull request by mikelieva**
Hi, this is my first time here, I'm catalan and I saw that the text has been translated so quick with grammar mistakes and bit "catalenglish"...so in my humble opinion now it's much better. ;) Just to help a bit to the master and riseup.net! TY so much; respectfully mkl_

### CODE REVIEW

**Comment by mikelieva** [comment]
Sorry for doing it splitted in several files... I'm a newbie ... ^^,

**Comment by dtto** [comment]
No problem! Thanks for your help.

**Comment by mikelieva** [comment]
Hi Is still the old text on the riseup. there are grammar mistakes, the word [apariència] in catalan doesn't exist; is [aparença] and is not [vivendes] is [habitatges].... IT BURN MY EYES it looks made from an SPANISH guy... wie call them "Catanyols" due they do this kind of MISTAKES.. pleas update it...IT'S A MESS!! TY

**Comment by elijh** [comment]
ok, sorry, forgot to deploy. new text should be available now.

**Pull request merged**
