### PR TITLE
Jabber is XMPP since 2004 #585

### PR DESCRIPTION
**Pull request by Neustradamus**
Jabber is XMPP since 2004:
- https://xmpp.org/

Linked to #585.

### CODE REVIEW

**Comment by Neustradamus** [comment]
@elijh: I have modified for have no conflicts.
After this validation, I will create a new PR for be perfect.

**Comment by Neustradamus** [comment]
Any news @elijh?

**Comment by elijh** [comment]
thank you! sorry for the delay

**Comment by Neustradamus** [comment]
@elijh thank you too, I continue changes!

**Comment by Neustradamus** [comment]
@elijh Last part done: https://github.com/riseupnet/riseup_help/pull/591

**Pull request merged**
