### PR TITLE
deleted spam/spamcop.en.text since it's not used (and a boatload of translations)

### PR DESCRIPTION
**Pull request by baldurmen**
This page is not published and its text is present on the spam page.

### CODE REVIEW

**Comment by baldurmen** [comment]
Ok, my bad, it's actually published on https://help.riseup.net/en/spamcop, but still, the text is the same as the spamcop section on the spam page.

**Comment by baldurmen** [comment]
Aaaaannd since I'm too lazy to create a new branch for this single commit, some other correction/translation commits might join the pull too.

If this causes problem, I'll do the work the right way if you ask.

**Comment by baldurmen** [comment]
Hmm, what about merging this pull?

**Comment by elijh** [comment]
sorry for the dely, sorry it took so long.

**Pull request merged**
