### PR TITLE
Fix issue #336

### PR DESCRIPTION
**Pull request by baldurmen**
Fix issue #336 by replacing Ubuntu by Linux Mint.

### CODE REVIEW

**Comment by elijh** [comment]
i don't think we want to recommend mint over ubuntu. why not just link to the ubuntu install page?

afaik, ubuntu is more responsive to security changes that need to be pushed out. (i won't even bring up the mint hack)

**Comment by baldurmen** [comment]
@elijh well if Riseup's official line if that Ubuntu is OK, I'll do this.

Then again, I do not trust Ubuntu anymore since the whole [Amazon search scandal](https://www.gnu.org/philosophy/ubuntu-spyware.en.html).

**Comment by kradan** [comment]
haha, why don't we pick one of [those](https://www.gnu.org/distros/free-distros.html)

**Comment by just1602** [comment]
Hello,

Since the majority of the birds use or have already use Debian, can we just choose this one as suggested distribution. Otherwise, Debian is:

* Really secure
* Has an installation UI (Like ubuntu)
* Make easy disk encryption during the installation (Like ubuntu)
* Is not bind with any corporation
* It'll allow us to avoid change this page every time a new trendy distribution based on Debian is release ! ;)

**Comment by kradan** [comment]
Am Tue, 09 Aug 2016 06:28:24 -0700
schrieb Justin Lavoie <notifications@github.com>:

> Since the majority of the birds use or have already use Debian, can
> we just choose this one as suggested distribution.
> * It'll allow us to avoid change this page every time a new trendy
> distribution based on Debian is release ! ;)

+1 :)

**Comment by A-red-BREASTED-robin** [comment]
May I randomly have permission to help fix ?

**Pull request closed without merging**
