### PR TITLE
Remove mention of red vpn and jabber pages

### PR DESCRIPTION
**Pull request by just1602**
I don't know if I should remove the OTR mention in message security?

It doesn't talk explicitly about jabber and pidgin/otr can be use on IRC, but let me know if you want me to remove those mentions.

### CODE REVIEW

**Comment by anarcat** [comment]
this seems a bit harsh, no? shouldn't /chat say something about the service going away instead?

**Comment by just1602** [comment]
@anarcat I thought it'd be a good idea to have a "riseup graveyard" page or something like that for deprecated services?

**Comment by anarcat** [comment]
On 2021-09-02 11:13:12, Justin Lavoie wrote:
> @anarcat I thought it'd be a good idea to have a "riseup graveyard" page or something like that for deprecated services?

maybe just some redirection?

-- 
Drowning people
Sometimes die
Fighting their rescuers.
                        - Octavia Butler

**Comment by disturbio** [comment]
XMPP requires a deprecation notice, while the configuration instructions removed... just something that if someone duckduckgoes "riseup.net chat" can get to a page saying, oops, this is gone. 

The VPN should be already using a redirection (i think)

**Comment by mkf** [comment]
> XMPP requires a deprecation notice, while the configuration instructions removed... just something that if someone duckduckgoes "riseup.net chat" can get to a page saying, oops, this is gone.
> 
> The VPN should be already using a redirection (i think)

Hi. I just changed my old Riseup username hoping to start using it for XMPP again. Took me an hour to arrive here. I was trying out different subdomains to have my client connect.

**Comment by just1602** [comment]
@mkf yeah, I've a [PR open](#806) to remove the last mention of chat in the riseup navbar. Let's hope it's going to be less confusing after that.

**Pull request merged**
