### PR TITLE
Moving Hackerspaces.org to In memoriam

### PR DESCRIPTION
**Pull request by sudoneuron**

### CODE REVIEW

**Comment by ahimsatravis** [comment]
Moving hackbloc.org to In memoriam

**Comment by micah** [comment]
Thanks for this PR! Can you point to somewhere that shows that Hackerspaces is no longer? I see their website and they say they aren't updating it anymore.

**Comment by sudoneuron** [comment]
> Thanks for this PR! Can you point to somewhere that shows that Hackerspaces is no longer? I see their website and they say they aren't updating it anymore.

Perhaps the server was down when I was checking. The website wasn't loading for me when I was checking to see if the links were up-to-date, but it loads fine for me now, so no need for that change I guess!

**Comment by micah** [comment]
Great, thanks!

**Pull request closed without merging**
