### PR TITLE
Adds french translation for better-web-browsing

### PR DESCRIPTION
**Pull request by gagzkrim**
It's NOT 100% done. An important part is missing : the names of the buttons to click in the browser settings. I don't have them in french, and my browser version doesn't even fit the english names of the orginal page!

### CODE REVIEW

**Comment by elijh** [comment]
i wonder if you have a newer or older version of the browser. the text is based on the versions that are in the latest ubuntu release.

**Comment by elijh** [comment]
for headings to work, there must be an empty line before and after:

```

h3. Désactivez les cookies tierce-partie

Les cookies tierce-partie servent notamment aux publicitaires à
suivre vos comportements de navigation. Ils sont exécrables et
n'ont aucune utilité légitime.
```

But NOT this:

```
h3. Désactivez les cookies tierce-partie
Les cookies tierce-partie servent notamment aux publicitaires à
suivre vos comportements de navigation. Ils sont exécrables et
n'ont aucune utilité légitime.
```

**Comment by gagzkrim** [comment]
I just upgraded Iceweasel to version 38, and adjusted the translation. I added a note saying with which versions I tried everything.
I think it's ready to be merged !

**Comment by gagzkrim** [comment]
is it gonna be published on the live site at some point?
thanks!

**Comment by elijh** [comment]
sorry for the delay, we usually try to update more frequently.

it is up: https://help.riseup.net/fr/security/network-security/better-web-browsing

there are still a few formatting things to fix.

also, this page does not look so good! https://help.riseup.net/fr/security

**Pull request merged**
