### PR TITLE
add script 'what_needs_an_update.sh'

### PR DESCRIPTION
**Pull request by kradan**
do you prefer to have it in a separate repo instead?

### CODE REVIEW

**Comment by baldurmen** [comment]
I wrote a nice python script that does that: https://gitlab.com/baldurmen/riseup-up-to-date

**Comment by kradan** [comment]
> I wrote a nice python script that does that:

There are differences.

Your script prints a list of files that need to be updated (i guess).

My script looks for translated files that have been translated before
the last change to the original. Then it shows the difference for the
original file since the last commit to the translation.

**Comment by baldurmen** [comment]
My point is that it seems to me having one tool that could do both would be better than two partial tools. I also think python is a more suitable scripting language for that kind of job, but I guess it's a very personal opinion.

I would be happy if you made a MR on the python script I wrote to add diff functionality.

**Comment by kradan** [comment]
i agree, unfortunately i won't be able to do it soon -
struggle finding time for translations already. also you are probably
more familiar with python. :)

**Pull request merged**
