### PR TITLE
update riseup key id to use long id

### PR DESCRIPTION
**Pull request by taggart**

### CODE REVIEW

**Comment by elijh** [comment]
hmm.... what??!! The CA used for black.riseup.net does not expire until:

    Not After: Sun Apr 28 00:00:00 UTC 2024

**Comment by elijh** [comment]
oh, maybe you mean that "red" uses this CA, but "black" does not?

**Comment by elijh** [comment]
why not?:

    [[verify and update->riseup-ca]]

**Comment by taggart** [comment]
yes, s/black/red/ and the shorter reference. Take a look at dkg's MR first (full key ids) and I will do another one.

**Pull request closed without merging**
