### PR TITLE
Add Delta Chat to list of supported clients

### PR DESCRIPTION
**Pull request by lefherz**
A first draft for a Delta Chat introduction page. Any suggestions for other topics which could be included?

@jankass could you maybe do a french translation or so? other input welcome as well :)

### CODE REVIEW

**Comment by lefherz** [comment]
Yeah, sorry for that. I will look into it during 36c3, if that's okay?

**Comment by micah** [comment]
That is great! :+1:

**Comment by lefherz** [comment]
Okay, that's fine so far :)

**Comment by micah** [comment]
Thanks for this! I've just merged it and after making sure it builds/renders fine, will deploy it.

**Comment by micah** [comment]
@lefherz I've gone ahead and deployed it, but I notice that the images are wider than the boarder, is it something that you can easily fix? 

See this: https://riseup.net/en/email/clients/delta-chat

**Comment by lefherz** [comment]
Actually, I thought `!{height:213px}` would fix it. I had the same problem in my local build, but for me `!{height:213px}` fixed it. The website doesn't show it in its style attributes. An option might be to resize the images to be smaller; but my hope would actually be to have them clickable. 213 pixels high is already veeery small, you can barely see anything on the screenshots.

**Comment by lefherz** [comment]
Maybe not using textile, but markdown or html would be an option? Seems to be a rendering bug in textile.

**Comment by lefherz** [comment]
which version of amber does your deployment use? I use 0.3.12.

**Comment by micah** [comment]
> Maybe not using textile, but markdown or html would be an option?
> Seems to be a rendering bug in textile.

Yeah, markdown would be preferred, we are trying to move everything to
markdown to eventually be able to migrate to hugo, so maybe that is the
way to go?

> which version of amber does your deployment use? I use 0.3.12.

same version :o

**Pull request merged**
