### PR TITLE
fix link to windows.ovpn file

### PR DESCRIPTION
**Pull request by taggart**

### CODE REVIEW

**Comment by elijh** [comment]
try instead:

    [[riseup.ovpn => windows-riseup.ovpn]]

**Comment by elijh** [comment]
(in other words, relative links are better than absolute one, and square bracket links are better than textile ones)

**Comment by taggart** [comment]
ok, but the problem was the missing extra windows/ directory. I'll fix.

**Comment by taggart** [comment]
oh I see what you mean, fixed.

**Pull request merged**
